Feature/slider setting
exadel-inc/ui-playground pull request #210
Opened 2021-11-23 20:19 UTC by Sisha3342

2021-11-24 15:44 UTC, nattallius approved these changes

2021-11-24 15:44 UTC, nattallius commented on src/settings/slider-setting/slider-setting.ts
> +  public static inconsistencyClass = 'inconsistency-marker';
I don't see any actual uses of this

2021-11-24 15:44 UTC, nattallius commented on src/settings/slider-setting/README.md
> +- *step* - step between range's values.
Maybe it's better to mention default values in README?

2021-11-24 15:45 UTC, nattallius commented on src/settings/slider-setting/slider-setting.ts
> +    this.$field.value = value || '0';
Maybe it's better to set `this.min` instead of hardcoded `'0'` ?

2021-11-25 06:39 UTC, AlexanderBazukevich approved these changes

2021-11-25 22:18 UTC, ala-n requested changes

2021-11-25 22:18 UTC, ala-n commented on src/settings/slider-setting/slider-setting.ts
> +  @attr({defaultValue: '1'}) public step: string;
It sounds like an '0' will be a more expectable value here

2021-11-25 22:18 UTC, ala-n commented on src/settings/slider-setting/slider-setting.ts
> +    if (this.$field) return;
I see a little bit of inconsistency here, we assume that the this.$field to be empty but at the same time
- we clear everything inside setting on the 30th line
- and we, basically, have no disconnected callback to make the field empty...

So as I see right now this custom element can not properly control its lifecycle.

2021-11-25 22:18 UTC, ala-n commented on src/settings/slider-setting/slider-setting.ts
> +    label.appendChild(this.$field);
Propose to move it to the separate method

2021-11-25 22:18 UTC, ala-n commented on src/settings/slider-setting/slider-setting.ts
> +  protected initSlider() {
You can create memoized getter to simplify and optimize things.

Somewhere in the class: 
```
@memoize
protected get $field() {
   const $field = document.createElement('input');
   $field.type = 'range';
   return $field; 
} 

@memoize
protected get $label() {
   const $label = document.createElement('label');
   $label.appendChild(this.$field);
   return $label; 
} 

protected updateConfiguration() {
    this.$field.min = this.min;
    this.$field.max = this.max;
    this.$field.step = this.step;
    // Better wrap the text to the span to easily control it or render it trough ::before { content: attr(label); }
    // this.$label.innerText = this.label;
}

```

In Constructor:
```
this.updateConfiguration();
this.innerHTML = '';
this.append(this.$label);
this.append(this.$fieldValue);
```

2021-11-25 22:18 UTC, ala-n commented on src/settings/slider-setting/slider-setting.ts
> +    this.$field.name = this.label;
'name' should be defined for the form fields, not sure that our field should relates to form

2021-11-25 22:18 UTC, ala-n commented on src/settings/slider-setting/slider-setting.ts
> +    this.$field.addEventListener('input', () => this.updateSliderValue());
There is no unsubscriber for that listener

2021-11-30 00:37 UTC, ala-n approved these changes

2021-11-30 00:37 UTC, ala-n commented on src/settings/slider-setting/slider-setting.ts
> +  };
```suggestion
  @bind
  protected updateSliderValue() {
    this.$fieldValue.textContent = `Value: ${this.$field.value}`;
  }
```

2021-11-30 00:37 UTC, ala-n commented on src/settings/slider-setting/slider-setting.ts
> +  }
Super cosmetic: place it near connected callback for consistency with other components.

2021-11-30 00:40 UTC, ala-n commented on src/settings/slider-setting/slider-setting.ts
> +  @attr({defaultValue: '1'}) public step: string;
Just in case: it sounds like I miss rid that it is a step but not a current value.

2021-11-30 11:54 UTC, merged

2022-04-22 18:00 UTC, yadamskaya commented
:tada: This PR is included in version 1.0.0-beta.9 :tada:

The release is available on [GitHub release](https://github.com/exadel-inc/ui-playground/releases/tag/v1.0.0-beta.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-06 12:57 UTC, yadamskaya commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/ui-playground/v/1.0.0)
- [GitHub release](https://github.com/exadel-inc/ui-playground/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: