feat(state): fire state changing as microtask
exadel-inc/ui-playground pull request #241
Opened 2022-01-19 13:30 UTC by nattallius

@exadel-inc/ui-playground-team

2022-01-19 15:53 UTC, yadamskaya approved these changes

2022-01-19 18:55 UTC, ala-n requested changes

2022-01-19 18:55 UTC, ala-n commented on src/core/base/model.ts
> +    Promise.resolve().then(() => this.fire());
It does not stack into a single call if multiple requests happen per task.

2022-01-19 18:57 UTC, ala-n commented on src/core/base/model.ts
> +    Promise.resolve().then(() => this.fire());
The purpose to make something in a microtask is to collect all the changes/requests per task and process the te result change once before the current makrotask ends

2022-01-31 17:33 UTC, ala-n approved these changes

2022-02-02 16:39 UTC, PolinaVolchetskaya approved these changes

2022-02-03 06:48 UTC, Sisha3342 approved these changes

2022-02-03 06:51 UTC, yadamskaya commented on src/core/base/model.ts
> +  protected promisifiedFiring() {
It may be better to use the verb for method name

2022-02-03 06:58 UTC, AlexanderBazukevich approved these changes

2022-02-14 11:50 UTC, merged

2022-04-22 18:00 UTC, yadamskaya commented
:tada: This PR is included in version 1.0.0-beta.9 :tada:

The release is available on [GitHub release](https://github.com/exadel-inc/ui-playground/releases/tag/v1.0.0-beta.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-06 12:57 UTC, yadamskaya commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/ui-playground/v/1.0.0)
- [GitHub release](https://github.com/exadel-inc/ui-playground/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: